export { default as theme } from "./theme";

export type {
  TBreakpoint,
  TBreakpointNames,
  TTypographicGrid,
  TCssNotations,
  TTypographicScale,
  TTypographicScaleNames,
  TLinearScaleSettings,
  TModularScaleSettings,
  TText,
  TFont,
  TFontNames,
  TFontWithName,
  TColor,
  TColorSpace,
  TColorSpaceNames,
  TColorNamesForThePalette,
  TStandardColorSpaceNames,
  THeadings,
  THeadingsSettings,
  TSpacingPresetNames,
  THeadingsPresetNames,
  TLinkStylePresetNames,
  TLinkStyle,
  TColorPair,
  TColorPairNames,
  TLinkTypePresetNames,
  TDecorations,
  TDecoration,
  TElementState,
  TTheme,
} from "./theme";
