export type {
  TTypography,
  TTypographicGrid,
  TTypographicScale,
  TTypographicScaleNames,
  TModularScaleSettings,
  TLinearScaleSettings,
  TText,
  TFont,
  TFontNames,
  TFontWithName,
  THeadings,
  THeadingsSettings,
  THeadingsPresetNames,
  TLinkStylePresetNames,
  TLinkStyle,
  TLinkStyleProps,
  TLinkTypePresetNames,
  TLinkStatusPresetNames,
} from "./typography";
export { default as typography } from "./typography";
